config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :users, :only => [:new, :create, :index, :show, :edit, :update]
  resources :measurements
  resources :workouts
  resources :exercises

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
    has_and_belongs_to_many :workouts
end

app/models/measurement.rb
class Measurement < ApplicationRecord
    belongs_to :user, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  has_many :measurements
  belongs_to :workout, :optional => true
  has_many :exercises, :through => :workouts
end

app/models/workout.rb
class Workout < ApplicationRecord
  has_many :users
  has_and_belongs_to_many :exercises
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    unless @current_user.present?
      flash[:error] = "You must be logged in"
      redirect_to login_path
    end
  end

  def check_for_admin
    redirect_to login_path unless (@current_user.present? && @current_user.admin?)
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :check_for_login

  def index
    @exercises = Exercise.all
  end

  def new
    @exercise = Exercise.new
  end

  def create
    exercise = Exercise.create exercise_params
    redirect_to exercise
  end

  def edit
    @exercise = Exercise.find params[:id]
  end

  def update
    exercise = Exercise.find params[:id]
    exercise.update exercise_params
    redirect_to exercise
  end

  def show
    @exercise = Exercise.find params[:id]
  end

  def destroy
    exercise = Exercise.find params[:id]
    exercise.destroy
    redirect_to exercises_path
  end

  private
  def exercise_params
    params.require(:exercise).permit(:name, :body_area, :description, :video)
  end
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  before_action :check_for_login

  def index
    @measurements = Measurement.all
    @counter = 0
  end

  def new
    @measurement = Measurement.new
  end

  def create
    measurement = Measurement.create measurement_params
    @current_user.measurements << measurement
    redirect_to measurement
  end

  def edit
    @measurement = Measurement.find params[:id]
  end

  def update
    measurement = Measurement.find params[:id]
    measurement.update measurement_params
    redirect_to measurement
  end

  def show
    @measurement = Measurement.find params[:id]
  end

  def destroy
    measurement = Measurement.find params[:id]
    measurement.destroy
    redirect_to measurements_path
  end

  private
  def measurement_params
    params.require(:measurement).permit(:weight, :height, :body_fat, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "User could not be created!"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    user = User.find params[:id]
    user.update user_params
    redirect_to user
  end

  def show
  end

  private
  def user_params
    params.require(:user).permit(:email, :name, :surname, :dob, :phone, :password, :password_confirmation, :workout_id)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :check_for_login

  def index
    @workouts = Workout.all
  end

  def new
    @workout = Workout.new
  end

  def create
    workout = Workout.create workout_params
    redirect_to workout
  end

  def edit
    @workout = Workout.find params[:id]
  end

  def update
    workout = Workout.find params[:id]
    workout.update workout_params
    redirect_to workout
  end

  def show
    @workout = Workout.find params[:id]
    def select
      @current_user.workout = @workout
      redirect_to user_path(@current_user)
    end
  end

  def destroy
    workout = Workout.find params[:id]
    workout.destroy
    redirect_to workouts_path
  end



  private
  def workout_params
    params.require(:workout).permit(:name, :category, :age_range, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
# Helpers for better embedding and manipulation of videos
# Place this code in app/helpers/videos_helper.rb
# Then from any view you can add:
#
#    <%= get_video_iframe('http://the.video.url') %>
#
# Optionally you can add width and height.
#
#    <%= get_video_iframe('http://the.video.url', '1600px', '900px') %>
#
# Thanks to https://stackoverflow.com/a/27878890/1498118

module VideosHelper

  require 'net/http'

  # Regex to find YouTube's and Vimeo's video ID
  YOUTUBE_REGEX = %r(^(http[s]*:\/\/)?(www.)?(youtube.com|youtu.be)\/(watch\?v=){0,1}([a-zA-Z0-9_-]{11}))
  VIMEO_REGEX = %r(^https?:\/\/(?:.*?)\.?(vimeo)\.com\/(\d+).*$)

  # Finds YouTube's video ID from given URL or [nil] if URL is invalid
  # The video ID matches the RegEx \[a-zA-Z0-9_-]{11}\
  def find_youtube_id url
    url = sanitize url
    matches = YOUTUBE_REGEX.match url.to_str
    if matches
      matches[6] || matches[5]
    end
  end

  # Get YouTube video iframe from given URL
  def get_youtube_iframe url, width, height
    youtube_id = find_youtube_id url

    result = %(<iframe title="YouTube video player" width="#{width}"
                height="#{height}" src="//www.youtube.com/embed/#{ youtube_id }"
                frameborder="0" allowfullscreen></iframe>)
    result.html_safe
  end

  # Finds Vimeo's video ID from given URL or [nil] if URL is invalid
  def find_vimeo_id url
    url = sanitize url
    matches = VIMEO_REGEX.match url.to_str
    matches[2] if matches
  end

  # Get Vimeo video iframe from given URL
  def get_vimeo_iframe url, width, height
    vimeo_id = find_vimeo_id url
    uri = "https://vimeo.com/api/oembed.json?url=https%3A//vimeo.com/#{ vimeo_id }&width=#{ width }&height=#{ height }"
    # see -> https://stackoverflow.com/a/4581095/1498118
    response = Net::HTTP.get( URI.parse( uri ))
    json = JSON.parse response
    json['html'].html_safe
  end

  # Main function
  # Return a video iframe
  # If the url provided is not a valid YouTube or Vimeo url it returns [nil]
  def get_video_iframe(url, width = "560px", height = "315px")
    if find_vimeo_id(url)
      get_vimeo_iframe(url, width, height)
    elsif find_youtube_id(url)
      get_youtube_iframe(url, width, height)
    end
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_form.html.erb
<%= form_for @exercise do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body_area %>
    <%= f.text_field :body_area, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :video %>
    <%= f.url_field :video, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<div class="container">
  <h1>Edit - <%= @exercise.name %></h1>
</div>
<div class="container">
  <%= render :partial => 'form' %>
</div>

app/views/exercises/index.html.erb
<div class="container">
  <h1>All Exercises</h1>
</div>

<div class="container">
  <% @exercises.each do |exercise| %>
    <ul>
      <li><%= link_to exercise.name, exercise %></li>
    </ul>
  <% end %>
</div>

<div class="container">
  <h2>
    <%= link_to 'Add a New Exercise', new_exercise_path, :class => 'btn btn-outline-primary' %>
  </h2>
</div>

app/views/exercises/new.html.erb
<div class="container">
  <h1>Add an Exercise</h1>
</div>
<div class="container">
  <%= render :partial => 'form' %>
</div>

app/views/exercises/show.html.erb
<div class="container">
  <h1><%= @exercise.name %></h1>
</div>

<div class="container">
  <ul>
    <li>Body Area: <%= @exercise.body_area %></li>
    <li>Description: <%= @exercise.description %></li>
    <li>Found in:
      <% @exercise.workouts.each do |exercise| %>
        <ul>
          <li><%= link_to exercise.name, workout_path(exercise) %></li>
        </ul>
      <% end %> </li>
    <li>Video:</li>
    <%= get_video_iframe(@exercise.video) %>
  </ul>
</div>

<div class="container">
  <div class="controls">
    <%= link_to 'Edit Exercise', edit_exercise_path(@exercise), :class => 'btn btn-outline-primary' %>
    <%= link_to 'Delete Exercise', @exercise, :method => 'delete', :data => { :confirm => 'Are you sure?'}, :class => 'btn btn-outline-primary' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workout App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
          <div class="navbar-brand">
            <%=  link_to 'Home', root_path %>
          </div>

          <% if @current_user.present?  %>
            <% if @current_user.admin? %>
              <div class="navbar-brand">
                <%= link_to 'Admin-Panel', users_path %>
              </div>
            <% end %>
            <div class="navbar-brand">
              <%=  link_to 'Profile', user_path(@current_user) %>
            </div>
            <div class="navbar-brand">
              <%=  link_to 'Measurements', measurements_path %>
            </div>
            <div class="navbar-brand">
              <%=  link_to 'Workouts', workouts_path %>
            </div>
            <div class="navbar-brand">
              <%=  link_to 'Exercises', exercises_path %>
            </div>
            <div class="navbar-brand">
              <%=  link_to "Log Out #{ @current_user.email }", login_path, :method => 'delete' %>
            </div>
          <% else %>
            <div class="navbar-brand">
              <%=  link_to 'Sign up', new_user_path %>
            </div>
            <div class="navbar-brand">
              <%=  link_to 'Log In', login_path %>
            </div>
          <% end %>
        </div>
      </nav>
    </div>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/measurements/_form.html.erb
<%= form_for @measurement do |f| %>
  <div class="form-group">
    <%= f.label :weight %>
    <%= f.text_field :weight, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :height %>
    <%= f.text_field :height, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body_fat %>
    <%= f.text_field :body_fat, :class => 'form-control' %>
  </div>
  <div class="form-group">
      <%= f.submit class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/measurements/edit.html.erb
<div class="container">
  <h1>Edit Measurement Data</h1>
</div>
<div class="container">
  <%= render :partial => 'form' %>
</div>

app/views/measurements/index.html.erb
<div class="container">
  <h1>Body Measurement Data for <%= @current_user.name %> </h1>
</div>

<div class="container">
  <h3>Body Weight Line Chart</h3>
  <%= line_chart @current_user.measurements.group_by_hour(:created_at).maximum(:weight)  %>
  <% @measurements.each do |measurement| %>
    <% if measurement.user_id == @current_user.id %>
      <h3>
        <% @counter = @counter + 1 %>
        <%= link_to "Entry ##{ @counter }", measurement%>
      </h3>
      <ul>
        <li>Weight: <%= measurement.weight %> kg</li>
        <li>Height: <%= measurement.height %> cm</li>
        <% if measurement.body_fat.present? %>
          <li>Body-fat: <%= measurement.body_fat %> %</li>
        <% end %>
        <li>Created at: <%= measurement.created_at.strftime '%l:%M %p - %B %e, %Y' %></li>
      </ul>
    <% end %>
  <% end %>
</div>

<div class="container">
    <h2>
      <%= link_to 'New Measurement', new_measurement_path, :class => 'btn btn-outline-primary' %>
    </h2>
</div>

app/views/measurements/new.html.erb
<div class="container">
  <h1>Add Measurement Data</h1>
</div>
<div class="container">
  <%= render :partial => 'form' %>
</div>

app/views/measurements/show.html.erb
<div class="container">
  <h1>Entry View</h1>
</div>

<div class="container">
  <h2><%= @measurement.created_at.strftime '%l:%M %p - %B %e, %Y' %> </h2>
</div>

<div class="container">
  <ul>
    <li>Weight: <%= @measurement.weight %> kg</li>
    <li>Height: <%= @measurement.height %> cm</li>
    <li>Body-fat: <%= @measurement.body_fat %> %</li>
  </ul>
</div>

<div class="container">
  <div class="controls">
    <%= link_to 'Edit Measurement', edit_measurement_path(@measurement), :class => 'btn btn-outline-primary' %>
    <%= link_to 'Delete Measurement', @measurement, :method => 'delete', :data => { :confirm => 'Are you sure?'}, :class => 'btn btn-outline-primary' %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <h1>Hardcore Workouts</h1>
</div>

<div class="container">
  <h4>
    <% if @current_user.present? %>
    You are logged in as <%= @current_user.email %>
    <% else %>
    Please log in or sign up!
    <% end %>
  </h4>
</div>

<div class="container mb-4 mt-4">
  <h5>
    Find the best workout routines and training plans for you to do at home or in the gym. Choose from killer Inferno and MAX workouts, single exercises, cardio, lower-body workouts, and more!
  </h5>
</div>

<div class="container mb-4 mt-4">
  <h5>
    Whether you’re into bodybuilding, power lifting, strength training or just getting started, these workouts and tips will help you reach your goals.
  </h5>
</div>

<div class="container">
  <iframe style="display: block; margin: auto;" width="560" height="315" src="https://www.youtube.com/embed/s8hWQwFwayo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>    
</div>

app/views/session/new.html.erb
<div class="container">
  <h1>Log In</h1>
</div>

<div class="container">
  <%= form_tag login_path do %>
      <div class="form-group">
        <%= label_tag :email %>
        <%= email_field_tag :email, nil, :class => 'form-control' %>
      </div>

      <div class="form-group">
        <%= label_tag :password %>
        <%= password_field_tag :password, nil, :class => 'form-control' %>
      </div>

      <div class="form-group">
        <%= submit_tag "Sign In", :class => 'btn btn-outline-primary' %>
      </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, :required => true, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, :required => true, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :required => true, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Sign up!", :class => 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <h1>Edit Profile</h1>
</div>

<div class="container">
  <% if @current_user.errors.any? %>
    <ol>
      <% @current_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ol>
  <% end %>
</div>

<div class="container">
  <%= form_for @current_user do |f| %>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, :required => true, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :surname %>
      <%= f.text_field :surname, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :dob %>
      <%= f.date_field :dob, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :phone %>
      <%= f.phone_field :phone, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :workout_id %>
      <%= f.select :workout_id, Workout.pluck(:name, :id), :include_blank => true, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit "Submit", :class => 'btn btn-outline-primary' %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1>Admin Panel</h1>
</div>

<div class="container">
  <h3>User's Emails</h3>
  <% @users.each do |user| %>
    <p><%= user.email %></p>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1>Sign Up</h1>
</div>
<div class="container">
  <% if @user.errors.any? %>
    <ol>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ol>
  <% end %>
</div>
<div class="container">
  <%= render :partial => 'form' %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1>My Profile - <%= @current_user.email %></h1>
</div>

<div class="container">
  <ul>
    <li>Email: <%= @current_user.email %></li>
    <li>Name: <%= @current_user.name %></li>
    <li>Surname: <%= @current_user.surname %></li>
    <li>Date of Birth: <%= @current_user.dob.strftime '%A, %B %e, %Y' if @current_user.dob.present? %></li>
    <li>Phone: <%= @current_user.phone %></li>
    <% if @current_user.workout.present? %>
    <li>Current workout: <%= link_to @current_user.workout.name, workout_path(@current_user.workout) %></li>
    <% end %>
    <li>Joined: <%= @current_user.created_at.strftime '%B %e, %Y' %></li>
  </ul>
</div>

<div class="container">
  <div class="controls">
    <%= link_to 'Edit Profile', edit_user_path(@current_user), :class => 'btn btn-outline-primary' %>
  </div>
</div>

app/views/workouts/_form.html.erb
<%= form_for @workout do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_field :category, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :age_range %>
    <%= f.text_field :age_range, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, :class => 'form-control' %>
  </div>
  <div class="form-group">
      <%= f.submit class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<div class="container">
  <h1>Edit - <%= @workout.name %></h1>
</div>
<div class="container">
  <%= render :partial => 'form' %>
</div>

app/views/workouts/index.html.erb
<div class="container">
  <h1>Workout Plans</h1>
</div>

<div class="container">
  <% @workouts.each do |workout| %>
    <ul>
      <li><%= link_to workout.name, workout %></li>
    </ul>
  <% end %>
</div>

<div class="container">
  <h3>
    <%= link_to 'Create a Workout Plan', new_workout_path, :class => 'btn btn-outline-primary' %>
  </h3>
</div>

app/views/workouts/new.html.erb
<div class="container">
  <h1>Create a Workout Plan</h1>
</div>
<div class="container">
  <%= render :partial => 'form' %>
</div>

app/views/workouts/show.html.erb
<div class="container">
  <h1><%= @workout.name %></h1>
</div>

<div class="container">
  <ul>
    <li>Category: <%= @workout.category %></li>
    <li>Age range: <%= @workout.age_range %></li>
    <li>Description: <%= @workout.description %></li>
    <li>Exercises:
    <% @workout.exercises.each do |workout| %>
      <ul>
        <li><%= link_to workout.name, exercise_path(workout) %></li>
      </ul>
    <% end %>
     </li>
  </ul>
</div>

<div class="container">
  <div class="controls">
    <div class="container mb-4">
      <%= button_to 'Select Workout', { :action => 'select' }, :data => { :confirm => 'Are you sure?'}, :class => 'btn btn-outline-primary' %>
    </div>

    <div class="container">
      <%= link_to 'Edit Workout', edit_workout_path(@workout), :class => 'btn btn-outline-primary' %>
      <%= link_to 'Delete Workout', @workout, :method => 'delete', :data => { :confirm => 'Are you sure?'} %>
    </div>
  </div>
</div>